### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Ramprits** [prisma/vscode-graphql#99] opened 2019-02-13 23:45 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-graphql`
- Extension Version: `0.1.6`
- OS Version: `Linux x64 4.15.0-34-generic`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/ramprit/Prisma.vscode-graphql-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by brian-cooney** [comment] 2019-02-15 10:35
I have experienced the same issue on macOS Mojave 10.14.2. Code helper showing average 60% CPU. resumed to normal when I disabled the extension.

**Comment by divyenduz** [comment] 2019-02-15 19:46
Closing as duplicate of https://github.com/prisma/vscode-graphql/issues/89. Please open a new issue if you think that these are separate issues. 

There is no reproduction of this, can you please share a minimal reproduction of the project that experiences this on #89 ? I would love to fix this as soon as possible but I am unable to reproduce. 

Thanks.

**Closed by divyenduz** 2019-02-15 19:46 UTC
